services:
  - type: web
    name: letssail-scraper
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python -m playwright install chromium
    startCommand: gunicorn main:app --bind 0.0.0.0:8000
